export const steps = [
  "site_created",
  "erp_installed",
  "scheduler_enabled",
  "locale_configured",
  "company_created",
  "fiscal_year_created",
  "global_defaults_set",
  "setup_completed",
  "regional_setup",
  "domains_activated",
  "fitdesk_configured",
  "app_installed_fitdesk",
  "api_keys_generated",
  "warmup_completed",
  "smoke_test_passed",
] as const;
